### ISSUE TITLE
Where's λ at in this code and what distinguishes Series Informed Activation Function from Depthwise Convolution?

### ISSUE THREAD

**Issue by AlphaPlusTT** [huawei-noah/VanillaNet#1]
The paper mentions λ in the Formula 1, could you please show me where it is located in this code?
And what's the difference between Series Informed Activation Function and relu + Depthwise Convolution?

**Comment by HantingChen** [comment]
λ locates in https://github.com/huawei-noah/VanillaNet/blob/f8385cf4ac0a5143431a05c84c5a40da4491b3d8/models/vanillanet.py#L139 and https://github.com/huawei-noah/VanillaNet/blob/f8385cf4ac0a5143431a05c84c5a40da4491b3d8/main.py#L449

The Series Informed Activation Function is implemented in relu + Depthwise Convolution, which is similar with BNET (paper: https://arxiv.org/pdf/2011.14150.pdf, code:https://github.com/yuhuixu1993/BNET) and FReLU (paper:https://arxiv.org/pdf/2007.11824.pdf, code:https://github.com/megvii-model/FunnelAct)

**Comment by AlphaPlusTT** [comment]
Thanks a lot, got it, Formula 1 is implemented in leaky_relu, a clever implementation approach.
