### ISSUE TITLE
complexity of activation function in Eq. (8)

### ISSUE THREAD

**Issue by PayloadJF** [huawei-noah/VanillaNet#15]
Hi, thanks for this brilliant work.

As previously mentioned, the activation layer should be applied after the corresponding convolutional layer. It appears that there may be a typo in the computation cost presented in Eq. (8), which should perhaps be H x W x Cout x n^2.

**Comment by HantingChen** [comment]
Hello,

Thank you for your attention to detail and for bringing this to my attention. I appreciate your input. I will certainly make the necessary corrections. Thank you again.

Best Regards.
