### ISSUE TITLE
Testing latency issue：VanillaNet 5-10

### ISSUE THREAD

**Issue by Learner-feng** [huawei-noah/VanillaNet#17]
I tested VanillaNet5-10 on the A100 server and the latency results are as follows:
<img width="326" alt="企业微信截图_16859357051341" src="https://github.com/huawei-noah/VanillaNet/assets/85987556/24921bcf-42c0-429f-92b4-247c77078011">
The code provided by the author was used for testing:
<img width="529" alt="企业微信截图_16859573082974" src="https://github.com/huawei-noah/VanillaNet/assets/85987556/2f1d1052-664f-46c8-b070-42ed383543bc">
Why is there such a significant difference? Could you please help identify where the problem might be?

**Comment by ggjy** [comment]
Hi, thanks for reporting this issue. I have updated the code. It seems that use ```net.switch_to_deploy()``` will cause this problem. I directly initialize the network by  ```net = vanillanet_5(deploy=True).cuda()``` (https://github.com/huawei-noah/VanillaNet/blob/main/test_latency.py#L23) can fix this problem.
