### ISSUE TITLE
十层的网络结构是怎么样的？

### ISSUE THREAD

**Issue by xiaohangguo** [huawei-noah/VanillaNet#25]
您好，很棒的工作，请问十层的网络结构是怎么样的？成倍数增加吗？如果可以的话，可以画一下简易网络图吗

**Comment by xiaohangguo** [comment]
您好，昨晚我用netron 可视化了网络结构，然后打算自己绘制一下，对论文里面的画图思路进行学习。我在进行相关的模型改进工作，如果可以的话，可以给我授权一下修改或者引用绘制模型图权利吗？
![image](https://github.com/huawei-noah/VanillaNet/assets/72799392/3f466f1e-e4d8-4daa-a232-b4a4deec0b16)

我想把网络的可视化模型图，进行二次创作，因为我发现论文里面给出了6th的模型图，但没有给出10th的模型图，其实他们一个是17 层一个是29层。10th在6th的基础上又堆叠了一些基础模块，这在我的数据集上表现很好，因此我需要在论文里面介绍和描述他们。

**Comment by HantingChen** [comment]
绘图工具使用的是：http://alexlenail.me/NN-SVG/LeNet.html ， 结构可以参考论文补充材料。

**Comment by xiaohangguo** [comment]
谢谢，已经画出来了，就是用的这个。不过我发现论文里面给出的5 10是某种规格，因为我发现5层的网络层数好像是14层，不知道有没有出错

**Comment by xiaohangguo** [comment]
你好，请问补充材料可以辛苦贴出来吗，我没找到，想深入研究一下，谢谢

**Comment by xiaohangguo** [comment]
在论文的最后面，sry，看到了
![image](https://github.com/huawei-noah/VanillaNet/assets/72799392/6eb48bbd-e4fe-497e-aa8d-2e966f5dbb6c)
