### ISSUE TITLE
Typo in Eq.(4)?

### ISSUE THREAD

**Issue by DoranLyong** [huawei-noah/VanillaNet#29]
Thanks to share your nice work. It gives some inspiration to my study. :)

If you don't mind, I'd like to ask if there's a typo in the formula in Eq. (4).

![Screenshot from 2023-06-21 15-02-21](https://github.com/huawei-noah/VanillaNet/assets/13333380/2f44b9c5-a8f3-4756-9dfa-c6c5ecf416b0)

I think the operator $*$ at the end should be $\cdot$ following the same format in Eq.(3).

**Comment by HantingChen** [comment]
Sorry for the mistake. We will fix it in the updated version. Thanks!
