### ISSUE TITLE
About the Deep Training Strategy in coco object detection task

### ISSUE THREAD

**Issue by julightzhong10** [huawei-noah/VanillaNet#3]
Hi, 

Thanks for the great work. 

For coco object detection task using the imagenet pre-trained model, do you still use Deep Training Strategy or tuning λ during training? If so, what is the tuning strategy?

Thanks for the reply

**Comment by ggjy** [comment]
We directly set λ=1 during the detection training.

**Comment by wsy-yjys** [comment]
why directly set λ=1 instead  of  gradually form 0 up to 1 ？

**Comment by ggjy** [comment]
We use the checkpoint trained from ImageNet (which is indeed λ=1 from the 2/3 training epochs when training on ImageNet). We also try the strategy gradually form 0 up to 1 in COCO, but there seems little difference in downstream fine-tuning (~0.1 mAP).

**Comment by wsy-yjys** [comment]
Ok, I see, thank you~

**Comment by PGthree3** [comment]
> 

你好，请问分割任务是否也不适合深度训练策略或者深度训练策略收效不大

**Comment by PGthree3** [comment]
你好，请问分割任务是否也不适合深度训练策略或者深度训练策略收效不大？

**Comment by PGthree3** [comment]
> 我们使用从 ImageNet 训练的检查点（当在 ImageNet 上训练时，它确实是来自 2/3 训练时期的 λ=1）。我们也在 COCO 中尝试逐渐从 0 到 1 的策略，但下游微调（~0.1 mAP）似乎差异不大。

你好，请问分割任务是不是也不适合深度训练策略或者深度训练策略收效不大？

**Comment by julightzhong10** [comment]
Thanks for the reply and discussion! Closing this issue
