### ISSUE TITLE
VanillaNet use 4*4 kernel

### ISSUE THREAD

**Issue by LUOBO123LUOBO123** [huawei-noah/VanillaNet#30]
Many chips are optimized for 3×3 kernel, will it be slow to use 4×4 kernel on the mobile ? For example, on the MTK chip.

**Comment by HantingChen** [comment]
Thanks for the nice suggestion. Since we use a stride 4 convolution, a 3*3 kernel will miss the information in the input features. Therefore, we use 4x4 kernel for the stem.
