### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by yueyue0112** [huawei-noah/VanillaNet#39]
Hi, thanks for sharing this useful work! I'm reading the program and there was something wrong when I debug 'main.py' (train). The problem is as following:
```
for ema_decay in args.model_ema_decay:
TypeError: 'float' object is not iterable
```
'args.model_ema_decay' was set 0.99996 as guideline.
Could you give some suggestions on the problem? Thanks a lot.

Yue.

**Comment by ggjy** [comment]
you can directly change the default ```args.model_ema_decay``` from 0.99996 to [0.99996], this for loop is used to train with multiple ema decay numbers simultaneously.

**Comment by yueyue0112** [comment]
Got it! It can work now. 
Thanks a lot!
