### ISSUE TITLE
AttributeError: 'VanillaNet' object has no attribute 'module'

### ISSUE THREAD

**Issue by RuiChen-stack** [huawei-noah/VanillaNet#40]
Hello, I encountered this issue during training：
 File "main.py", line 560, in <module>
    main(args)
  File "main.py", line 448, in main
    if 'VanillaNet' == model.module.__class__. __name__ and epoch <= args.decay_epochs:
  File "/mnt/data/anaconda3/envs/satnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'VanillaNet' object has no attribute 'module'

**Comment by ggjy** [comment]
Hi, you can change that code to ```if 'VanillaNet' == model.class. name```, I thinks the difference lies in whether the model is wrapped with torch.distributed?

**Comment by RuiChen-stack** [comment]
> Hi, you can change that code to `if 'VanillaNet' == model.class. name`, I thinks the difference lies in whether the model is wrapped with torch.distributed?

Yes, you're right. When I used torch. distributed, this problem disappeared
